# Generated by Django 2.2.6 on 2019-10-10 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20191010_0358'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sample',
            new_name='Project',
        ),
        migrations.RenameField(
            model_name='descriptionitem',
            old_name='sample',
            new_name='project',
        ),
    ]
