# Generated by Django 2.2.6 on 2019-10-19 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20191019_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='blurb',
            field=models.TextField(default='a', max_length=500),
            preserve_default=False,
        ),
    ]
