# Generated by Django 2.2.6 on 2019-10-19 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_blurb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='blurb',
            field=models.TextField(),
        ),
    ]
