# Generated by Django 2.2.6 on 2019-10-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20191019_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='languages',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='platforms',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
